version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 5000:5000
    container_name: frontend-container
    environment:
      - ENV REACT_APP_BACKEND_URL=http://localhost:80
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - ENV REQUEST_ORIGIN=http://localhost:80
    container_name: backend-container
    depends_on:
      - postgres
      - redis
  redis:
    image: redis
    container_name: redis-container
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    container_name: postgres-container
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    container_name: nginx-container
    depends_on:
      - frontend
      - backend
