version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 5000:5000
    container_name: frontend-container_name
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - 8080:8080
    container_name: backend-container
