version: '3.8'

services:
  frontend:
    container_name: frontend-container
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 5000:5000
  backend:
    container_name: backend-container
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - 8080:8080
